notifications:
  email: false
env:
  - RELEASE_BRANCH="master"
language: c
os:
- linux
- osx
sudo: required
services:
  - docker
git:
  submodules: true
compiler:
- gcc
addons:
  apt:
    packages:
    - build-essential
    - gcc
    - make
    - valgrind
    - zsh
    - musl-tools
    - mingw-w64

before_install:
- git submodule update --init --recursive
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash ; fi

script:
- mkdir -p build
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then   make clean && make osx && make check-shared && cp -v src/zenroom-shared build/zenroom.x86; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make clean && make static && make check-static && cp -v src/zenroom-static build/zenroom.x86; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make clean && make win && cp -v src/zenroom.exe build/ ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make clean && docker exec -it emscripten make js && docker exec -it emscripten make check-js && cp -v src/zenroom.js build/ ; fi

deploy:
  - provider: releases
    api_key:
      secure: lHmD0cuCkAxWT4s4s7HX8Wz4qrpm8XBbz1GT/Ei56iZJAUTtTEQqAyqD22MnqnBAtpOlSHx/S92iok/VAWmW22H9PD58cob7oimfmkViJq/xLg1x7EW2xVQL2tDF+eB2Rv2iQQ9UBuIy9jSftnlZSs3RBiLzFQDrSLTZe2KDOLrGk4WAuHGpl568jWuHAGNVmSBLSekhw1ucQQhy77qSz/zLp7XH09/Qrk0iYqoVSqgx4wKoeNFHHgq2EB67t1/ar2PAAUHMkpYSxxqNog0wr4OVpOtxBj0f1HJ5gdsAZUXpFyownymZc3fC2UMMJwjgUTcOCnlDW7GUw/kEMneXaGKAlHoH5r7r5gXk4pDCGA4gsk4TMkXwu0rJ6mOKgyKc9XWjBJoCvp2+uFMkEiwQA/VUU9GdoyxH4uKc6VjZo9YajJ89DjV4djr7l6E+0AWHaIo1TvdD5LiaXwM836afzXegwHGEC6yxL4TqZYdyLetxLRweIHY9E9D3Lb9y8qkQU5ZmGxdNV5BK2PmmzupV8Va4wwk5ONnRTAwYWmpmTTBll7DwE98HvmW/yDqIPlyGWk0/pGsCJSnxTbAnu1uns0qQrljpTCms46cezCiWZhlKcFwBucQ0999LOULKPTffVHzRdc4HLWW5XUVQsnlE8kiWALhayiE+Y3wgiPvAgP8=
    file: build/zenroom.x86
    skip_cleanup: true
    draft: true
    name: Zenroom $TRAVIS_TAG (Apple/OSX build)
    on:
      tags: true
      repo: DECODEproject/zenroom
      branch: "$RELEASE_BRANCH"
      condition: $TRAVIS_OS_NAME = osx
  - provider: releases
    api_key:
      secure: lHmD0cuCkAxWT4s4s7HX8Wz4qrpm8XBbz1GT/Ei56iZJAUTtTEQqAyqD22MnqnBAtpOlSHx/S92iok/VAWmW22H9PD58cob7oimfmkViJq/xLg1x7EW2xVQL2tDF+eB2Rv2iQQ9UBuIy9jSftnlZSs3RBiLzFQDrSLTZe2KDOLrGk4WAuHGpl568jWuHAGNVmSBLSekhw1ucQQhy77qSz/zLp7XH09/Qrk0iYqoVSqgx4wKoeNFHHgq2EB67t1/ar2PAAUHMkpYSxxqNog0wr4OVpOtxBj0f1HJ5gdsAZUXpFyownymZc3fC2UMMJwjgUTcOCnlDW7GUw/kEMneXaGKAlHoH5r7r5gXk4pDCGA4gsk4TMkXwu0rJ6mOKgyKc9XWjBJoCvp2+uFMkEiwQA/VUU9GdoyxH4uKc6VjZo9YajJ89DjV4djr7l6E+0AWHaIo1TvdD5LiaXwM836afzXegwHGEC6yxL4TqZYdyLetxLRweIHY9E9D3Lb9y8qkQU5ZmGxdNV5BK2PmmzupV8Va4wwk5ONnRTAwYWmpmTTBll7DwE98HvmW/yDqIPlyGWk0/pGsCJSnxTbAnu1uns0qQrljpTCms46cezCiWZhlKcFwBucQ0999LOULKPTffVHzRdc4HLWW5XUVQsnlE8kiWALhayiE+Y3wgiPvAgP8=
    file: build/zenroom.exe
    skip_cleanup: true
    draft: true
    name: Zenroom $TRAVIS_TAG (Win64 build)
    on:
      tags: true
      repo: DECODEproject/zenroom
      branch: "$RELEASE_BRANCH"
      condition: $TRAVIS_OS_NAME = linux
  - provider: releases
    api_key:
      secure: lHmD0cuCkAxWT4s4s7HX8Wz4qrpm8XBbz1GT/Ei56iZJAUTtTEQqAyqD22MnqnBAtpOlSHx/S92iok/VAWmW22H9PD58cob7oimfmkViJq/xLg1x7EW2xVQL2tDF+eB2Rv2iQQ9UBuIy9jSftnlZSs3RBiLzFQDrSLTZe2KDOLrGk4WAuHGpl568jWuHAGNVmSBLSekhw1ucQQhy77qSz/zLp7XH09/Qrk0iYqoVSqgx4wKoeNFHHgq2EB67t1/ar2PAAUHMkpYSxxqNog0wr4OVpOtxBj0f1HJ5gdsAZUXpFyownymZc3fC2UMMJwjgUTcOCnlDW7GUw/kEMneXaGKAlHoH5r7r5gXk4pDCGA4gsk4TMkXwu0rJ6mOKgyKc9XWjBJoCvp2+uFMkEiwQA/VUU9GdoyxH4uKc6VjZo9YajJ89DjV4djr7l6E+0AWHaIo1TvdD5LiaXwM836afzXegwHGEC6yxL4TqZYdyLetxLRweIHY9E9D3Lb9y8qkQU5ZmGxdNV5BK2PmmzupV8Va4wwk5ONnRTAwYWmpmTTBll7DwE98HvmW/yDqIPlyGWk0/pGsCJSnxTbAnu1uns0qQrljpTCms46cezCiWZhlKcFwBucQ0999LOULKPTffVHzRdc4HLWW5XUVQsnlE8kiWALhayiE+Y3wgiPvAgP8=
    file: build/zenroom.x86
    skip_cleanup: true
    draft: true
    name: Zenroom $TRAVIS_TAG (Linux build)
    on:
      tags: true
      repo: DECODEproject/zenroom
      branch: "$RELEASE_BRANCH"
      condition: $TRAVIS_OS_NAME = linux
  - provider: releases
    api_key:
      secure: lHmD0cuCkAxWT4s4s7HX8Wz4qrpm8XBbz1GT/Ei56iZJAUTtTEQqAyqD22MnqnBAtpOlSHx/S92iok/VAWmW22H9PD58cob7oimfmkViJq/xLg1x7EW2xVQL2tDF+eB2Rv2iQQ9UBuIy9jSftnlZSs3RBiLzFQDrSLTZe2KDOLrGk4WAuHGpl568jWuHAGNVmSBLSekhw1ucQQhy77qSz/zLp7XH09/Qrk0iYqoVSqgx4wKoeNFHHgq2EB67t1/ar2PAAUHMkpYSxxqNog0wr4OVpOtxBj0f1HJ5gdsAZUXpFyownymZc3fC2UMMJwjgUTcOCnlDW7GUw/kEMneXaGKAlHoH5r7r5gXk4pDCGA4gsk4TMkXwu0rJ6mOKgyKc9XWjBJoCvp2+uFMkEiwQA/VUU9GdoyxH4uKc6VjZo9YajJ89DjV4djr7l6E+0AWHaIo1TvdD5LiaXwM836afzXegwHGEC6yxL4TqZYdyLetxLRweIHY9E9D3Lb9y8qkQU5ZmGxdNV5BK2PmmzupV8Va4wwk5ONnRTAwYWmpmTTBll7DwE98HvmW/yDqIPlyGWk0/pGsCJSnxTbAnu1uns0qQrljpTCms46cezCiWZhlKcFwBucQ0999LOULKPTffVHzRdc4HLWW5XUVQsnlE8kiWALhayiE+Y3wgiPvAgP8=
    file: build/zenroom.js
    skip_cleanup: true
    draft: true
    name: Zenroom $TRAVIS_TAG (Javascript build)
    on:
      tags: true
      repo: DECODEproject/zenroom
      branch: "$RELEASE_BRANCH"
      condition: $TRAVIS_OS_NAME = linux

