language: c
os:
  - linux
  - osx

sudo: required

git:
  submodules: true

compiler:
  - gcc

addons:
  artifacts:
    s3_region: s3-eu-central-1
    working_dir: src
    paths:
      - zenroom-shared
  apt:
    packages:
      - build-essential
      - gcc
      - make
      - valgrind
      - zsh

before_install:
  - git submodule update --init --recursive

script:
  - make shared
  - make check-shared
