language: c
os:
- linux
- osx
sudo: required
git:
  submodules: true
compiler:
- gcc
addons:
  apt:
    packages:
    - build-essential
    - gcc
    - make
    - valgrind
    - zsh
before_install:
- git submodule update --init --recursive
script:
- make shared
- make check-shared

deploy:
  provider: releases
  api_key:
    secure: lHmD0cuCkAxWT4s4s7HX8Wz4qrpm8XBbz1GT/Ei56iZJAUTtTEQqAyqD22MnqnBAtpOlSHx/S92iok/VAWmW22H9PD58cob7oimfmkViJq/xLg1x7EW2xVQL2tDF+eB2Rv2iQQ9UBuIy9jSftnlZSs3RBiLzFQDrSLTZe2KDOLrGk4WAuHGpl568jWuHAGNVmSBLSekhw1ucQQhy77qSz/zLp7XH09/Qrk0iYqoVSqgx4wKoeNFHHgq2EB67t1/ar2PAAUHMkpYSxxqNog0wr4OVpOtxBj0f1HJ5gdsAZUXpFyownymZc3fC2UMMJwjgUTcOCnlDW7GUw/kEMneXaGKAlHoH5r7r5gXk4pDCGA4gsk4TMkXwu0rJ6mOKgyKc9XWjBJoCvp2+uFMkEiwQA/VUU9GdoyxH4uKc6VjZo9YajJ89DjV4djr7l6E+0AWHaIo1TvdD5LiaXwM836afzXegwHGEC6yxL4TqZYdyLetxLRweIHY9E9D3Lb9y8qkQU5ZmGxdNV5BK2PmmzupV8Va4wwk5ONnRTAwYWmpmTTBll7DwE98HvmW/yDqIPlyGWk0/pGsCJSnxTbAnu1uns0qQrljpTCms46cezCiWZhlKcFwBucQ0999LOULKPTffVHzRdc4HLWW5XUVQsnlE8kiWALhayiE+Y3wgiPvAgP8=
  file: src/zenroom-shared
  skip_cleanup: true
  draft: true
  name: Zenroom $TRAVIS_TAG (OSX build)
  on:
    tags: true
    repo: DECODEproject/zenroom
    branch: master
    condition: $TRAVIS_OS_NAME = osx
